import type { Session, User } from '@supabase/supabase-js';

/**
 * Represents the allowed user roles within the Xiris platform.
 */
export type UserType = 'cliente' | 'tecnico';

/**
 * Possible lifecycle states for a user account.
 */
export type UserStatus =
  | 'active'
  | 'inactive'
  | 'suspended'
  | 'pending_verification';

/**
 * Possible lifecycle states for a technician application.
 */
export type ApplicationStatus =
  | 'submitted'
  | 'under_review'
  | 'approved'
  | 'rejected';

/**
 * Availability flags used to expose technician presence information.
 */
export type AvailabilityStatus = 'online' | 'offline' | 'busy';

/**
 * Specific status values reported by the technician availability switch.
 */
export type TechnicianPresenceStatus = 'offline' | 'available' | 'busy';

/**
 * Current workflow states for client originated service requests.
 */
export type ServiceRequestStatus =
  | 'requested'
  | 'searching'
  | 'candidate_ready'
  | 'accepted'
  | 'cancelled';

/**
 * Core user profile information shared by both clients and technicians.
 */
export interface Profile {
  /** Unique identifier generated by the database (UUID). */
  id: string;
  /** Primary e-mail address used for authentication. */
  email: string;
  /** Full name for display purposes. */
  full_name: string | null;
  /** Optional phone number supplied by the user. */
  phone: string | null;
  /** Optional avatar image stored in Supabase Storage or external URL. */
  avatar_url: string | null;
  /** User role that determines available functionality within the app. */
  user_type: UserType;
  /** Legacy role metadata stored in the profile record. */
  role?: string | null;
  /** Current account status reflecting onboarding or suspension state. */
  status: UserStatus;
  /** ISO string recording when the profile was created. */
  created_at: string;
  /** ISO string recording when the profile was last updated. */
  updated_at: string;
}

/**
 * Extended data specific to technicians registered on the platform.
 */
export interface TechnicianProfile {
  /** UUID matching the associated profile id. */
  id: string;
  /** List of skill categories or specialties offered by the technician. */
  specialties: string[];
  /** Geographic areas where the technician provides services. */
  service_areas: string[];
  /** Average rating computed from completed service reviews. */
  rating: number;
  /** Total number of services fulfilled through the platform. */
  total_services: number;
  /** Indicates whether the technician passed the verification process. */
  is_verified: boolean;
  /** Arbitrary documents used during verification. */
  verification_documents: Record<string, unknown>;
  /** Technician availability status for new assignments. */
  availability_status: AvailabilityStatus;
  /** Real-time coordinates when location sharing is enabled. */
  current_location: { lat: number; lng: number } | null;
  /** ISO creation timestamp for the technician profile. */
  created_at: string;
}

/**
 * Current presence information emitted from the technician dashboard.
 */
export interface TechnicianStatus {
  technician_id: string;
  is_online: boolean;
  current_status: TechnicianPresenceStatus;
  current_lat: number | null;
  current_lng: number | null;
  updated_at: string | null;
}

/**
 * Canonical representation of a service request stored in Supabase.
 */
export interface ServiceRequest {
  id: string;
  client_id: string;
  assigned_technician_id: string | null;
  status: ServiceRequestStatus;
  problem_description: string | null;
  location_lat: number | null;
  location_lng: number | null;
  created_at: string;
  updated_at: string;
}

/**
 * Offer emitted by the matchmaking engine for a specific service request.
 */
export interface ServiceRequestOffer {
  id: string;
  service_request_id: string;
  technician_id: string;
  status: 'pending' | 'accepted' | 'rejected';
  expires_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Additional attributes for client accounts.
 */
export interface ClientProfile {
  /** UUID matching the associated profile id. */
  id: string;
  /** Optional billing or service address. */
  address: string | null;
  /** Saved payment preference supplied by the client. */
  preferred_payment_method: string | null;
  /** Total number of service requests created by the client. */
  total_requests: number;
  /** ISO creation timestamp for the client profile. */
  created_at: string;
}

/**
 * Aggregated representation of a profile and its role specific data.
 */
export type DatabaseProfile = Profile & {
  /** Technician specific fields when the user_type is `tecnico`. */
  technician_profile?: TechnicianProfile;
  /** Client specific fields when the user_type is `cliente`. */
  client_profile?: ClientProfile;
};

/**
 * Structured representation of a technician onboarding application.
 */
export interface TechnicianApplication {
  /** Primary key generated by the database. */
  id: string;
  /** Foreign key referencing the applicant profile. */
  user_id: string | null;
  /** Contact e-mail captured at submission time. */
  email: string;
  /** Applicant full name. */
  full_name: string | null;
  /** Applicant phone number. */
  phone: string | null;
  /** List of declared skills. */
  skills: string[] | null;
  /** Narrative describing prior experience. */
  experience: string | null;
  /** Storage path of the uploaded CV file. */
  cv_url: string | null;
  /** Storage paths for certification documents. */
  certs_urls: string[] | null;
  /** Current review status. */
  status: ApplicationStatus;
  /** Reviewer profile identifier when assigned. */
  reviewer_id: string | null;
  /** Optional reviewer notes. */
  review_notes: string | null;
  /** Timestamp for when the application was reviewed. */
  reviewed_at: string | null;
  /** Creation timestamp recorded by the database. */
  created_at: string;
  /** Update timestamp recorded by the database. */
  updated_at: string;
}

/**
 * Data required to register a new account through Supabase Auth.
 */
export interface SignUpData {
  /** Email used for authentication. */
  email: string;
  /** Password supplied during sign-up. */
  password: string;
  /** Display name captured during onboarding. */
  full_name?: string | null;
  /** Optional contact number collected at registration. */
  phone?: string | null;
  /** Role selected for the new account. */
  user_type: UserType;
  /** Optional structured data persisted as user metadata. */
  metadata?: Record<string, unknown>;
}

/**
 * Credentials required to authenticate an existing user.
 */
export interface SignInData {
  /** Email supplied by the user. */
  email: string;
  /** Password submitted during sign-in. */
  password: string;
  /** Optional one-time password for MFA flows. */
  otp?: string;
  /** Whether the session should persist beyond the current browser tab. */
  rememberMe?: boolean;
}

/**
 * Patch payload for updating a user profile.
 */
export interface UpdateProfileData {
  /** Profile identifier to update. */
  id: string;
  /** Partial set of profile fields. */
  profile?: Partial<
    Pick<Profile, 'full_name' | 'phone' | 'avatar_url' | 'status'>
  >;
  /** Optional technician profile adjustments. */
  technician_profile?: Partial<
    Omit<TechnicianProfile, 'id' | 'created_at'>
  >;
  /** Optional client profile adjustments. */
  client_profile?: Partial<
    Omit<ClientProfile, 'id' | 'created_at'>
  >;
}

/**
 * Normalised response returned after performing an authentication action.
 */
export interface AuthResponse {
  /** Supabase user representation. */
  user: User | null;
  /** Active session data returned by Supabase. */
  session: Session | null;
  /** Optional hydrated profile tied to the authenticated user. */
  profile?: DatabaseProfile | null;
  /** Error message when the authentication attempt fails. */
  error?: string;
}
